---
title: "STAC51A2Q2"
output:
  word_document: default
  html_notebook: default
---

```{r}
#2i)
# H0 theta = 1
# H1 theta > 1
theta = 1
n1 <- 4
n2 <- 4
x <- 0:4
e <- exp(1)

#sub in n=log(theta)
choose(n1, 3)*choose(n2,1)*e^(3*log(theta))/sum(choose(n1,x)*choose(n1,4-x)*e^(x*log(theta)))

```
One-sided p-value > 0.05, cannot reject H0 : θ = 1.

j) Calculate the exact p-value for testing the null hypothesis H0 : η = 0.1 versus the alternative H1 : η > 0.1 using the data in part (i) above. Run your R code with this data and comment on your results.

```{r}
# H0 : η = 0.1
# H1 : η > 0.1
# η = log(theta) => 0.1 = log(theta) => theta = e^0.1
theta = e^0.1

#generate table
table <- array(data = c(3,1,1,3), dim = c(2,2), dimnames = list(Study = c("Case","Control"),Exposure = c("Yes", "No")))
table

#exact test
fisher.test(table, or = theta, alternative="greater")

```
Answer: large P-value > 0.05, cannot reject H0 that η = 0.1.

k)
```{r}
likelihood <- function(n) {
  choose(n1, 3)*choose(n2,1)*e^(3*n)/sum(choose(n1,x)*choose(n1,4-x)*e^(x*n))
}
curve(likelihood, -3, 3, xlab="n", ylab="likelihood(n)")
#MLE in terms of n
optimize(likelihood, c(-3,3), maximum = TRUE)

#convert from n to theta to get conditional MLE
exp(1.857597)
```

